[package]
name = "barkle"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite"] }
tabled = "0.16.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
