name: qa
on:
  push:
    branches:
      - 'main'
  pull_request:
env:
  RUSTFLAGS: "-Dwarnings"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add clippy
      - name: Check format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add clippy
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: barkle
          path: target/release/barkle
          retention-days: 3
